### PR TITLE
Windows: update to GDAL 3.2.1 and fix for UCRT support

### PR DESCRIPTION
**Pull request by jeroen**
This upgrades you to the latest version of GDAL on Windows, and also prepares for upcoming UCRT toolchains.

### CODE REVIEW

**Comment by rnuske** [comment]
Thank you @jeroen !
Merged your Pull request and am on the way to submit to CRAN.

**Comment by rnuske** [comment]
Hi @jeroen
do you know how to get rid of [CRAN's UCRT warnings](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/apcf-00check.html) `failed to apply patch patches/CRAN/apcf.diff` ?

thanks
  robert

**Comment by jeroen** [comment]
That will automatically disappear when CRAN removes apcf from the list of packages that needed manual patching to work for ucrt. You don't need to do anything, they will do that at some point.

**Comment by rnuske** [comment]
Alright, thank you very much for the reassurance.

**Pull request merged**
